"""What build this is, so "which one am I running?" has an answer.

WHY THIS EXISTS
The app is a frozen executable that is rebuilt often and copied around by hand. Two
of them look identical, and a stale one behaves like the code that built it -- which
has already cost real confusion: a UI change was made, committed and then reported
missing, because the exe on disk predated it and nothing on screen said so.

So every build carries an identity, and it is shown in the launcher and written at
the top of every log.

HOW THE STAMP IS MADE
VERSION is the hand-set line; bump it deliberately. The rest is generated:
scripts/build-*.{bat,command} write build_stamp.py just before PyInstaller runs,
recording the commit and the build time. That file is gitignored -- it is an
artefact of a build, not a source of truth, and committing it would guarantee it
was wrong for everyone who did not run that exact build.

Run from a checkout there is no stamp, so git is asked directly. That is the more
honest answer there anyway: a working tree can be dirty, and the version should
say so rather than quietly claiming to be the commit it is sitting on.
"""
from __future__ import annotations

import datetime
import pathlib
import subprocess
import proc

# Bump deliberately. Nothing generates this.
VERSION = "0.1.0"


def _from_stamp() -> tuple[str, str] | None:
    """(commit, built) recorded at build time, if this is a built app."""
    try:
        import build_stamp                                    # type: ignore
        return getattr(build_stamp, "COMMIT", ""), getattr(build_stamp, "BUILT", "")
    except Exception:
        return None


def _from_git() -> tuple[str, str] | None:
    """(commit, built) asked of git, for a run from a checkout.

    Marks a dirty tree, because "0.1.0 (d6efa1d)" on a tree with uncommitted
    changes is a claim about code that is not what is running.
    """
    root = pathlib.Path(__file__).resolve().parent.parent
    try:
        sha = proc.run(["git", "-C", str(root), "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True, timeout=5)
        if sha.returncode != 0:
            return None
        commit = sha.stdout.strip()
        dirty = proc.run(["git", "-C", str(root), "status", "--porcelain"],
                               capture_output=True, text=True, timeout=5)
        if dirty.returncode == 0 and dirty.stdout.strip():
            commit += "+dirty"
        return commit, "from source"
    except Exception:
        return None


def info() -> dict:
    got = _from_stamp() or _from_git() or ("", "")
    return {"version": VERSION, "commit": got[0], "built": got[1]}


def describe() -> str:
    """One line for a title bar, a log header or an about box."""
    i = info()
    bits = [f"v{i['version']}"]
    if i["commit"]:
        bits.append(i["commit"])
    if i["built"]:
        bits.append(i["built"])
    return f"{bits[0]} ({', '.join(bits[1:])})" if len(bits) > 1 else bits[0]


def write_stamp(dest: pathlib.Path, commit: str) -> None:
    """Called by the build scripts. Overwrites any previous stamp."""
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    dest.write_text(
        "# Generated by scripts/build-*. Not source; see src/version.py.\n"
        f'COMMIT = "{commit}"\n'
        f'BUILT = "{now}"\n',
        encoding="utf-8")
